services:
  bot:
    build: .
    container_name: alpaca_bot
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./bot.log:/app/bot.log
      - ./trade_log.csv:/app/trade_log.csv
      - ./fills_log.csv:/app/fills_log.csv
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: alpaca_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: alpaca_grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
    - "3001:3000"


volumes:
  grafana_data: {}
